spring:
  datasource:
    url: jdbc:h2:file:./data/powerplant
    driver-class-name: org.h2.Driver
    password: password
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true